name: 'Hackathon Helper'
description: 'Helps to succeed the next hackathon.'
author: 'umgefahren'
inputs:
  issue_number:
    required: true
    description: 'The issue under which you want the hackathon progress comment.'
  hackathon_end:
    required: true
    description: 'When the hackathon will end formatted in MM/dd/yyyy hh:mm:s.'
  my_token:
    required: true
    description: 'The GitHub token.'
  
runs:
  using: 'node16'
  main: 'dist/index.js'
